### ISSUE TITLE
homeworlds: remove warning that gemini homeworlds are strongly disadvantaged

### ISSUE THREAD

**Issue by jdonland** [AbstractPlay/gameslib#3]
Currently, the game warns that selecting homeworld stars of the same size (i.e. a so-called Gemini homeworld) "puts you at a strong disadvantage". Current opening theory does not support this claim.

**Comment by Perlkonig** [comment]
Thanks for the feedback! Because I'm not particularly familiar with the "state of play," I started a conversation on the Discord. I tagged you. Please come join us there. Now's a good time to revisit *all* the warnings and make sure they are all current and helpful. And welcome! Thanks for playing with us!
